import { Draft } from "@/components/Draft";
import type { FaqItem } from "@/components/Faq";
import { config } from "./config";
import Link from "next/link";

const P = ({ children }: { children: React.ReactNode }) => <p>{children}</p>;

export function faqItems(turnaround: string): FaqItem[] {
  const support = config.supportEmail();
  const items: [string, string, React.ReactNode][] = [
    ["what", "What exactly is TRIPATROP?", <><P>TRIPATROP is a personalized European trip-planning service. You tell us your dates, budget, interests and travel style, and we research and organize a trip around you.</P><P>We focus on the details that make a trip actually work — destinations, routes, transportation, stays, activities, events, timing and practical logistics.</P></>],
    ["agency", "Are you a travel agency?", <><P>TRIPATROP is positioned as a trip-planning and research service rather than a traditional package-tour seller.</P><P>We do not sell you a bundled vacation through the website. Your flights, accommodations, transportation and activities are booked directly by you with the relevant third-party providers.</P><Draft>Confirm this description is consistent with the legal requirements applicable to the business&apos;s jurisdiction before publishing.</Draft></>],
    ["reservations", "Do you make the reservations for me?", <><P>No.</P><P>We research and organize the recommendations and provide booking links.</P><P>You complete the reservation and payment directly with the airline, hotel, transportation company, attraction or other provider.</P></>],
    ["book-myself", "Why do I book everything myself?", <><P>Because we want you to remain in control of your travel purchases.</P><P>Your reservations are made directly with the providers, your confirmations come from them and you can review their final price and terms before paying.</P></>],
    ["markup", "Do you add a markup to my flights or hotels?", <><P>TRIPATROP charges a separate planning fee.</P><P>We do not add a TRIPATROP booking markup to travel products that you purchase directly from third-party providers through the recommendations we send you.</P><Draft>If TRIPATROP ever uses affiliate links or receives a referral commission, disclose it here and wherever required.</Draft></>],
    ["cost", "How much does it cost?", <><P>The standard Personal Trip Design service is $199.</P><P>You begin with a $49 Trip Design deposit.</P><P>If you decide to continue with one of your trip directions, the remaining planning balance is $150.</P><P>Travel expenses themselves are not included in the $199 planning fee.</P></>],
    ["49", "What does the $49 get me?", <><P>The $49 starts the personalized research process.</P><P>We review your questionnaire and develop three personalized trip directions based on your dates, budget and interests.</P><P>These are designed to help determine the right trip before we spend time researching every individual booking.</P><P>One reasonable revision to the selected direction is included.</P></>],
    ["three-options", "Are the three options complete itineraries?", <><P>No.</P><P>They&apos;re trip directions.</P><P>They show you different ways your vacation could work, including the destinations, route, number of nights, general experiences, approximate transportation approach and estimated budget direction.</P><P>Once you choose one, we can build the detailed version.</P></>],
    ["150", "What does the remaining $150 get me?", <><P>It turns your selected direction into the complete TRIPATROP trip plan.</P><P>Depending on your trip, that may include detailed flight recommendations, accommodations, transportation, attractions, activities, events, restaurants, nightlife, practical logistics, estimated costs and direct booking links.</P></>],
    ["change", "What if I like one option but want to change something?", <><P>That&apos;s normal.</P><P>One reasonable revision to your selected trip direction is included.</P><P>For example: &ldquo;We love Option B, but can we spend fewer nights in Paris and add Amsterdam?&rdquo;</P><P>Major changes that effectively create a new trip may require additional planning and should be agreed upon before extra work begins.</P></>],
    ["dislike", "What if I don't like any of the three directions?", <><P>Contact us and tell us what&apos;s missing.</P><P>We&apos;ll first use the included revision process to understand what needs to change.</P><P>The rules for completed research are set out in our <Link className="link" href="/terms">Terms &amp; Conditions</Link> and <Link className="link" href="/refund-policy">Refund Policy</Link>.</P></>],
    ["refundable", "Is the $49 refundable?", <><P>Refunds follow TRIPATROP&apos;s published <Link className="link" href="/refund-policy">Refund &amp; Cancellation Policy</Link> and applicable consumer law.</P><Draft>Replace this answer with your legally reviewed policy: when the deposit becomes non-refundable, what happens if work has already started, and any cancellation rights that apply.</Draft></>],
    ["prices-change", "Can prices change?", <><P>Yes.</P><P>Travel pricing and availability can change quickly.</P><P>Any price we show is based on the information available when we research your trip.</P><P>The final price is always the price displayed by the provider when you make your reservation.</P></>],
    ["cheapest", "Do you guarantee the cheapest possible price?", <><P>No.</P><P>We look for options that make sense for your trip and budget, but we cannot guarantee that any recommendation is the absolute lowest price available anywhere.</P><P>Price is also not the only factor. Sometimes a slightly more expensive flight or hotel can save hours of travel time or put you in a much better location.</P></>],
    ["museums", "Can you find cheaper museum tickets?", <><P>We&apos;ll research official admission options and other legitimate booking options relevant to your trip.</P><P>If an attraction offers lower-priced days, free-entry periods or other useful admission options during your dates, we&apos;ll flag them when reliable information is available.</P><P>We do not guarantee discounts.</P></>],
    ["events", "Can you find events happening during my trip?", <><P>Yes. Relevant events can be part of the research.</P><P>Depending on your interests and destination, this may include football matches, sports, concerts, festivals, markets, exhibitions, nightlife and seasonal events.</P><P>Availability and schedules can change.</P></>],
    ["football", "Can you plan football trips?", <><P>Yes.</P><P>Tell us which club, league or type of football experience you&apos;re interested in.</P><P>We can incorporate relevant matches, stadium experiences or football-related activities when they fit your dates and route.</P><P>Ticket availability is never guaranteed.</P></>],
    ["nightlife", "Can you plan nightlife-focused trips?", <><P>Absolutely.</P><P>Tell us how important nightlife is in your questionnaire. We can consider nightlife neighborhoods, bars, clubs, beach clubs and relevant events when designing the trip.</P></>],
    ["honeymoon", "Can you plan a honeymoon?", <P>Yes. Use the questionnaire to tell us the atmosphere you&apos;re looking for, your budget and anything special you have in mind.</P>],
    ["family", "Can you plan family trips?", <P>Yes. Tell us who is traveling, including children&apos;s ages where relevant, and we&apos;ll take that into account when designing the trip.</P>],
    ["solo", "Can you plan solo travel?", <P>Yes.</P>],
    ["one-city", "Can you plan just one city?", <><P>Yes. A great trip doesn&apos;t need five countries.</P><P>We can build around one city, one region, one country or multiple countries.</P></>],
    ["no-idea", "What if I have no idea where I want to go?", <><P>Perfect.</P><P>Choose &ldquo;Surprise Me&rdquo; and tell us the kind of experience you want. We&apos;ll use your dates, budget and interests to develop possible directions.</P></>],
    ["budget", "Can you work with a strict budget?", <><P>Yes. Budget is one of the major factors we consider.</P><P>However, we cannot guarantee that every requested destination or experience will be realistic within every budget. If something doesn&apos;t make sense, we&apos;ll tell you and suggest alternatives.</P></>],
    ["transport", "Can you help with transportation inside Europe?", <P>Yes. We can compare the practicality of trains, flights, ferries, buses, rental cars and local transportation depending on the trip.</P>],
    ["visas", "Do you help with visas or passports?", <><P>We can point travelers toward official government information where appropriate, but TRIPATROP does not provide legal or immigration advice.</P><P>Travelers remain responsible for ensuring that they have the correct passport, visa, entry documents and other legal requirements for their trip.</P></>],
    ["insurance", "Do you sell travel insurance?", <><P>Not through the standard planning service unless explicitly stated otherwise.</P><P>Travelers should evaluate whether travel insurance is appropriate for their circumstances and review the terms of any policy carefully.</P></>],
    ["cancels", "What happens if an airline cancels my flight?", <><P>Your reservation is directly with the airline or travel provider.</P><P>Changes, cancellations, refunds and disruptions relating to a travel purchase are governed by that provider&apos;s terms and applicable law.</P><P>TRIPATROP can provide planning guidance if additional assistance is offered, but we do not control third-party providers.</P></>],
    ["turnaround", "How quickly will I receive my trip directions?", <P><strong>Current turnaround: {turnaround === "[OWNER TO SET]" ? <span className="ph">[OWNER TO SET]</span> : turnaround}</strong></P>],
    ["delivery", "How will I receive everything?", <P>Primarily by email. Your Trip ID is included in every message so we can easily keep track of your request.</P>],
    ["account", "Do I need an account?", <><P>No. TRIPATROP is intentionally simple.</P><P>Complete the questionnaire, pay the deposit and we&apos;ll communicate with you by email.</P></>],
    ["secure", "Is my payment secure?", <><P>Payments are processed by our secure third-party payment provider, Stripe.</P><P>TRIPATROP does not directly store your complete card details.</P></>],
    ["human", "Can I contact a real person?", <><P>Yes. TRIPATROP is built around personal trip planning.</P><P>Contact: <a className="link" href={`mailto:${support}`}>{support}</a> or use our <Link className="link" href="/contact">contact form</Link>.</P></>],
  ];
  return items.map(([id, q, a]) => ({ id, q, a }));
}
